"""
detection.py - the brain of Provenance Guard.

Two independent signals look at a piece of text:
  1. llm_signal()  - asks Groq (an LLM) how AI-like the text reads. Semantic.
  2. stylometry()  - measures the statistical SHAPE of the text. Structural.

Then we combine their scores into one confidence number (p_ai), turn that into an
attribution (likely_ai / uncertain / likely_human), and turn THAT into a reader-facing
transparency label.

All the tunable numbers (weights and thresholds) live up top so they're easy to see and
match exactly what planning.md says.
"""

import os
import re
import json
import statistics

from dotenv import load_dotenv
from groq import Groq

load_dotenv()  # reads GROQ_API_KEY out of the .env file into the environment

# --- tunable constants (must match planning.md) ---------------------------------------

LLM_WEIGHT = 0.65          # how much the LLM signal counts toward the final score
STYLE_WEIGHT = 0.35        # how much stylometry counts

THRESHOLD_AI = 0.70        # p_ai >= this  -> likely_ai   (deliberately high)
THRESHOLD_HUMAN = 0.45     # p_ai <  this  -> likely_human (anything between is uncertain)

GROQ_MODEL = "llama-3.3-70b-versatile"

# Create the Groq client once and reuse it.
_client = Groq(api_key=os.environ.get("GROQ_API_KEY"))


def _clamp(x, lo=0.0, hi=1.0):
    """Keep a number inside [lo, hi]."""
    return max(lo, min(hi, x))


# =======================================================================================
# Signal 1: LLM semantic judgment
# =======================================================================================

def llm_signal(text):
    """
    Ask Groq how likely the text is AI-generated.

    Returns a dict: {"score": float 0-1, "rationale": str}
    where score is the model's estimated probability that the text is AI-written.

    If the API call fails for any reason, we fall back to a neutral 0.5 so the rest of
    the system keeps working instead of crashing the request.
    """
    prompt = (
        "You are an AI-content detector for a writing platform. Estimate the probability "
        "that the text below was generated by an AI model, on a 0.0 to 1.0 scale. Use the "
        "full range and be decisive. Scoring guide:\n"
        "- 0.0-0.2: clearly human. Personal voice, specific lived detail, idiosyncrasy, "
        "casual phrasing, or small imperfections.\n"
        "- 0.4-0.6: genuinely mixed or hard to tell.\n"
        "- 0.8-1.0: clearly AI. Generic, hedged, formulaic 'balanced' prose with filler "
        "transitions ('It is important to note', 'Furthermore', 'In conclusion') and no "
        "real personal voice.\n"
        "IMPORTANT: formal, academic, or non-native human writing is NOT automatically AI. "
        "Specific, substantive content with a real argument should score LOWER than generic "
        "filler, even when the tone is formal. Avoid false accusations.\n"
        "Respond ONLY with JSON: "
        '{"ai_probability": <number 0 to 1>, "rationale": "<one short sentence>"}.\n\n'
        f"TEXT:\n{text}"
    )
    try:
        resp = _client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.0,  # low temperature -> more stable, repeatable scores
            response_format={"type": "json_object"},  # forces valid JSON back
            max_tokens=200,
        )
        data = json.loads(resp.choices[0].message.content)
        score = _clamp(float(data.get("ai_probability", 0.5)))
        rationale = str(data.get("rationale", "")).strip()
        return {"score": score, "rationale": rationale}
    except Exception as e:
        return {"score": 0.5, "rationale": f"LLM unavailable, used neutral score ({e})"}


# =======================================================================================
# Signal 2: stylometry (pure Python, no external libraries)
# =======================================================================================

def _split_sentences(text):
    """Rough sentence split on . ! ? - good enough for measuring sentence lengths."""
    parts = re.split(r"[.!?]+", text)
    return [p.strip() for p in parts if p.strip()]


def _words(text):
    """All word tokens, lowercased."""
    return re.findall(r"\b\w+\b", text.lower())


def _count_informal_markers(text):
    """
    Count casual/irregular writing markers. Humans use lots of these; AI text is clean.
      - contractions (don't, i'm, we're)
      - ellipses (...)
      - doubled punctuation (!! ?! ??)
      - lowercase sentence starts (a line that begins with a lowercase letter)
      - ALL-CAPS emphasis words (2+ letters)
    """
    markers = 0
    markers += len(re.findall(r"\b\w+'\w+\b", text))             # contractions
    markers += len(re.findall(r"\.\.\.", text))                  # ellipses
    markers += len(re.findall(r"[!?]{2,}", text))                # !! ?! ??
    markers += len(re.findall(r"(?:^|[.!?]\s+)[a-z]", text))     # lowercase starts
    markers += len(re.findall(r"\b[A-Z]{3,}\b", text))           # ALL CAPS emphasis (3+, so "AI"/"US" don't count)
    return markers


def stylometry(text):
    """
    Measure the structural shape of the text.

    Returns a dict with:
      "score"          : 0-1 stylometric AI-likeness (the part that feeds confidence)
      "burstiness_ai"  : 0-1 sub-score from sentence-length variation
      "informality_ai" : 0-1 sub-score from casual markers
      "metrics"        : raw numbers (reported for transparency, some not scored)
      "reliable"       : False when the text is too short for stylometry to mean much
    """
    sentences = _split_sentences(text)
    words = _words(text)
    word_count = len(words)

    sentence_lengths = [len(_words(s)) for s in sentences]
    # Population stdev; needs 2+ sentences to be meaningful.
    stdev = statistics.pstdev(sentence_lengths) if len(sentence_lengths) >= 2 else 0.0
    mean_len = statistics.mean(sentence_lengths) if sentence_lengths else 0.0

    ttr = len(set(words)) / word_count if word_count else 0.0
    markers = _count_informal_markers(text)
    markers_per_100 = (markers / word_count * 100) if word_count else 0.0

    # Too short to trust burstiness -> mark unreliable and stay neutral on that sub-score.
    reliable = len(sentence_lengths) >= 3 and word_count >= 40

    burstiness_ai = _clamp((6.0 - stdev) / 6.0) if reliable else 0.5
    informality_ai = _clamp(1.0 - markers_per_100 / 3.0)

    # Informality is the stronger structural discriminator (casual human writing is full
    # of markers; AI text is clean), so it leads. Burstiness is noisier on short text.
    score = 0.35 * burstiness_ai + 0.65 * informality_ai

    return {
        "score": round(score, 4),
        "burstiness_ai": round(burstiness_ai, 4),
        "informality_ai": round(informality_ai, 4),
        "reliable": reliable,
        "metrics": {
            "sentence_count": len(sentence_lengths),
            "word_count": word_count,
            "sentence_length_stdev": round(stdev, 3),       # scored (via burstiness)
            "informal_markers_per_100w": round(markers_per_100, 3),  # scored
            "type_token_ratio": round(ttr, 3),              # reported only
            "mean_sentence_length": round(mean_len, 3),     # reported only
        },
    }


# =======================================================================================
# Combine -> classify -> label
# =======================================================================================

def combine(llm_score, style_score):
    """Weighted average of the two signals -> p_ai (our confidence the text is AI)."""
    return round(LLM_WEIGHT * llm_score + STYLE_WEIGHT * style_score, 4)


def classify(p_ai):
    """Turn the confidence number into one of three attributions."""
    if p_ai >= THRESHOLD_AI:
        return "likely_ai"
    if p_ai < THRESHOLD_HUMAN:
        return "likely_human"
    return "uncertain"


def make_label(p_ai):
    """Map the confidence number to the exact reader-facing label text."""
    attribution = classify(p_ai)

    if attribution == "likely_ai":
        pct = round(p_ai * 100)
        return (
            f"🤖 Likely AI-generated. Our automated analysis suggests this content was "
            f"probably created with significant AI assistance (estimated {pct}% likelihood). "
            f"This is an automated estimate, not a verdict, and detection isn't perfect. "
            f"If you're the creator and think this is wrong, you can appeal and a human "
            f"will review it."
        )
    if attribution == "likely_human":
        pct = round((1 - p_ai) * 100)
        return (
            f"✍️ Likely human-written. Our automated analysis didn't find strong signs of "
            f"AI generation (estimated {pct}% likelihood this is human-written). This is a "
            f"probability, shown just for context."
        )
    # uncertain
    pct = round(p_ai * 100)
    return (
        f"❓ Uncertain. We couldn't confidently tell whether this is human- or AI-written "
        f"(estimated {pct}% AI-likelihood). Rather than guess, we're marking it inconclusive."
    )


def analyze(text):
    """
    Run the whole pipeline on a piece of text and return the pieces the endpoint needs.
    Kept here (not in app.py) so it's easy to test the detection on its own.
    """
    llm = llm_signal(text)
    style = stylometry(text)
    p_ai = combine(llm["score"], style["score"])
    return {
        "confidence": p_ai,
        "attribution": classify(p_ai),
        "label": make_label(p_ai),
        "signals": {
            "llm_score": llm["score"],
            "llm_rationale": llm["rationale"],
            "style_score": style["score"],
            "style_detail": style,
        },
    }
